name: Generate Docs

on:
  push:
    branches:
      - master

permissions:
  contents: write
  id-token: write
  actions: read  

jobs:
  build-docs:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install requirements
        run: pip install -r tools/requirements.txt

      - name: Generate docs
        run: pydoctor --project-name=StickFirmware --project-url=https://github.com/stickfirmware/stick --make-html --html-output=docs src/modules --theme readthedocs
        continue-on-error: true

      - name: Upload GitHub Pages artifact
        uses: actions/upload-pages-artifact@v4.0.0
        with:
          path: docs/
          
  deploy:
    runs-on: ubuntu-latest
    needs: build-docs
    steps:
      - name: Deploy GitHub Pages site
        uses: actions/deploy-pages@v4.0.5         
