name: Ruff
on:
  push:
    branches:
      - "master"
      - "dev"

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4.2.2

    - name: Setup Python
      uses: actions/setup-python@v5.6.0
      with:
        python-version: '3.x'
        
    - name: "Check ruff"
      uses: astral-sh/ruff-action@v3
      with:
        args: "check"
        src: "./src"
      
    - name: "Check imports sorting"
      uses: astral-sh/ruff-action@v3
      with:
        args: "check --select I"
        src: "./src"

    - name: Comment on pr if error
      if: failure()
      run: gh pr comment --body "Your code may not pass ruff checks (Import sorting and code style), please see checks for more info (commit ${{ github.sha }})."
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
